### ISSUE TITLE
Support Guids?

### ISSUE THREAD

**Issue by benhysell** [ckimes89/graphql-net#35]
Just started playing around and hit a roadblock, all of our ID fields are Guids.

Any idea what it might take to add Guid support?  Is this a 10 minute fix, or something that would take considerable effort?

**Comment by ckimes89** [comment]
Hey Ben,

Just got back from a vacation so I'll take a closer look at this tomorrow.
I thought that Guids were already supported, but we may have broken
something during some previous major refactorings. It should be a quick fix
if it's not working.

**Comment by benhysell** [comment]
I added a pull request with MS Sql tests using LocalDB, see #36

**Comment by ckimes89** [comment]
I added a test for loading a guid field using both an in-memory context and a SQLite context. Both are passing as expected, but I had to fix a minor issue with the DeepEquals method in the tests that was breaking for Guids.

The expected value that was being loaded from JSON was being read by Newtonsoft as a JObject with type of String. However, when creating a JObject from a Guid, the resulting JObject has a type of Guid. This was causing the deep equals to fail.

Where were you seeing issues with Guids? Was it trying to extend the current tests, or were you using the library from a NuGet package? If the latter, could you include some code and a stack trace so I could diagnose the issue?

**Comment by benhysell** [comment]
I was seeing this issue with ID fields using MS SQL and EF Core.  EF 6.1.3? produces the same issue.  See the pull request I submitted with failing tests.

https://github.com/ckimes89/graphql-net/pull/36

**Comment by ckimes89** [comment]
The tests in the pull request are expected to fail, since the guids (actual values) are being compared to ints (expected values). The expected values for test results are all listed here:

https://github.com/ckimes89/graphql-net/blob/master/Tests/GenericTests.cs

The idea behind the generic tests is not necessarily obvious, so I'll explain it here. I would like the library to work exactly the same regardless of the provider backing the IQueryable. Right now, I have support and tests for in-memory IQueryables (LINQ to Objects) and Entity Framework.

Since the results for each provider should be the exact same, I would like them to run against the same tests. So, all of the tests that are provider-independent are defined in `GenericTests.cs`. Each of the contexts are then implemented in their own projects (`Tests/InMemoryExecutionTests.cs` and `Tests.EF/EntityFrameworkExecutionTests.cs`).

So, if you were to implement a third context that used EF and MS SQL rather than SQLite, I would expect it to work properly (assuming no major differences between the SQLite and MS SQL providers for EF). However, if you change all of the integers to Guids rather than ints, then all of the generic tests should fail because of the type mismatch.

**Comment by ckimes89** [comment]
I added support for Guids as input parameters, which I believe was causing the problem you were seeing. If you're using the NuGet package let me know so I can push a minor update.

**Comment by benhysell** [comment]
Awesome for the fix!  Yes, I am using the NuGet package

**Comment by ckimes89** [comment]
I've updated NuGet to version 0.2.1, which should include this change.

**Comment by benhysell** [comment]
I'm up and running!  This is awesome, and thank you!

Now I need to wrap my head around how to get this into my system...
